### ISSUE TITLE
Feature request: Try inferring project's Godot version

### ISSUE THREAD

**Issue by KMouratidis** [MakovWait/godots#1]
![image](https://github.com/MakovWait/godots/assets/26832680/2eed15a3-26fd-4892-b9bf-e2df2d0fb3a5)

Instead of picking the latest version like shown above, are you able to infer a project's versions? E.g. the project I was trying to import here has this in the `project.godot` file:

```
config_version=5

[application]
...
config/features=PackedStringArray("4.1")
```

Another has `config/features=PackedStringArray("4.0", "Forward Plus")`, and so do a few more. Not sure if this is available for 3.x versions, but it seems consistent for 4.x.

**Comment by MrEliptik** [comment]
It doesn't seem available in Godot 3, but can be used for Godot 4!
