### ISSUE TITLE
Linux Import missing root directories

### ISSUE THREAD

**Issue by cloewen8** [MakovWait/godots#101]
When attempting to import a project in `/mnt/Home/Documents/Godot`, the mnt root directory is not displayed in the file browser.
![image](https://github.com/user-attachments/assets/166ae139-524d-478c-9ccc-fb032ca77ae2)

The expected behavior would be to either include the missing directories or use the native file browser (like Godot):
![image](https://github.com/user-attachments/assets/2517dc4e-359b-47b7-8f52-61a3b8a751b1)

A native file browser is preferable, however I'm not a fan of how it stores a copy of the editing project in `/run/user/1000`. I'm uncertain if this is specific to Godot or the Dolphin file browser.

**Comment by MakovWait** [comment]
There is an option in settings that allows to use the native file picker. Does it resolve the issue?

**Comment by cloewen8** [comment]
Just noticed the Flatpack version (1.0) is outdated. The latest version (1.3) works correctly and shows the mnt directory. I also checked with the native file browser to make sure and it also displays the directory.
