### ISSUE TITLE
Flatpak packaging

### ISSUE THREAD

**Issue by CharlieQLe** [MakovWait/godots#17]
Not really sure if this is the best place to put it, but I created a repository [here](https://github.com/CharlieQLe/io.github.MakovWait.Godots) with a Flatpak manifest for any Linux Flatpak users that may want to use multiple versions of Godot under a Flatpak install, something that isn't quite so easy normally. Right now, it has to be built from source, but it's pretty quick and it gets automatically integrated into the desktop.

Ideally, this would be built from source instead of pulling a binary and be published to Flathub for automatic updates. Once I figure out how headless Godot builds work, I can get started on that.

**Comment by CharlieQLe** [comment]
@MakovWait Since the flatpak now builds the project from source, publishing it to Flathub is the next step. With your permission, may I start a PR to get it onto Flathub?

**Comment by MakovWait** [comment]
Hey cool!
I believe yes, but I've never worked with Flathub and stuff so I'm wondering should I know about something? Ideally, it would be cool if I were free from all the possible responsibilities, then I'd have nothing against! 

And if the project is built from sources know, how the whole fluthub-deploy-stuff looks like? Is it automatic and triggers from main branch changes etc.

**Comment by CharlieQLe** [comment]
> Hey cool! I believe yes, but I've never worked with Flathub and stuff so I'm wondering should I know about something? Ideally, it would be cool if I were free from all the possible responsibilities, then I'd have nothing against!
> 
> And if the project is built from sources know, how the whole fluthub-deploy-stuff looks like? Is it automatic and triggers from main branch changes etc.

I'll probably handle maintaining and updating the flatpak build. Whenever a new stable update comes out, I would have to manually update the manifest, which usually will take a few minutes. Then the Flathub builder will automatically build and deploy the flatpak as needed. Flathub is strict about not using the latest git versions, focusing on stable releases instead. I'll begin the PR and link it here for anyone interested.

**Comment by FrostBird347** [comment]
The flathub version is still on 1.3 when 1.4 has been out for over a month.
