### ISSUE TITLE
Feaure request: Scan directory & mass-import

### ISSUE THREAD

**Issue by KMouratidis** [MakovWait/godots#2]
The default Godot editor has a `scan` option that crawls a whole directory and imports projects. Could you also do something like that? 

As for how this should look like, maybe try adding another window after the scan with all the imported projects (one per line) and a dropdown per project for editor selection? Or maybe you can leave them without mapping them to an editor and ask the user to pick an editor the first time they run them?

**Comment by MrEliptik** [comment]
It could also be done for scanning already installed editors

**Comment by MakovWait** [comment]
Done for projects. Do we need it for editors? If so, does someone have an idea how to be sure that given executable is Godot executable?

**Comment by KMouratidis** [comment]
In Windows, it might be possible by inspecting properties:
![image](https://github.com/MakovWait/godots/assets/26832680/e8f50340-f691-499b-99f4-b6734baea152)

In Mac, you might be able to read the `Godot.app/Contents/Info.plist`:
![image](https://github.com/MakovWait/godots/assets/26832680/e7049def-d37c-4eed-99b8-1d5707b138ed)

Unfortunately, for Linux files I can't find a solution. It might be that such data does not get exported. I would suggest trying `--version` which is a convention most Linux programs use, but I've come across some that didn't (plus this approach essentially requires executing the file). Google pointed me to exiftool 

```
~$ exiftool Godot_v4.0-beta6_linux.x86_64
ExifTool Version Number         : 12.40
File Name                       : Godot_v4.0-beta6_linux.x86_64
Directory                       : .
File Size                       : 111 MiB
File Modification Date/Time     : 2022:11:23 08:31:26+01:00
File Access Date/Time           : 2023:08:28 11:44:16+02:00
File Inode Change Date/Time     : 2023:08:28 11:44:00+02:00
File Permissions                : -rw-r--r--
File Type                       : ELF executable
File Type Extension             :
MIME Type                       : application/octet-stream
CPU Architecture                : 64 bit
CPU Byte Order                  : Little endian
Object File Type                : Executable file
CPU Type                        : AMD x86-64

~$ exiftool Godot_v3.5.2-stable_win64.exe
ExifTool Version Number         : 12.40
File Name                       : Godot_v3.5.2-stable_win64.exe
...
File OS                         : Win32
...
Company Name                    : Godot Engine
File Description                : Godot Engine
File Version                    : 3.5.2
Product Name                    : Godot Engine
Licence                         : MIT
Legal Copyright                 : Copyright (c) 2007-2023 Juan Linietsky, Ariel Manzur and contributors
Info                            : https://godotengine.org
Product Version                 : 3.5.2.stable.official
```

Maybe a hacky workaround like grepping the binary?

```
~$ grep -a AUTHORS.md Godot_v4.0-beta6_linux.x86_64
/* Copyright (c) 2014-2022 Godot Engine contributors (cf. AUTHORS.md).   */
Copyright (c) 2014-2022 Godot Engine contributors (cf. AUTHORS.md).

~$ grep -a AUTHORS.md Godot_v3.5.2-stable_x11.64
Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md).
```

**Comment by MrEliptik** [comment]
I feel like checking the filename should be enough, especially if the user points to a directory where the godot binaries are installed.
