### ISSUE TITLE
Save config to project folder

### ISSUE THREAD

**Issue by denovodavid** [MakovWait/godots#23]
Firstly, thank you very much for this tool, it is excellent :)

I'm mostly on Godot 4 now, but I know that Godot 3.x projects don't store their version number in `project.godot`. Perchance if there was an option to pin/save the version number to a file in the game project folder, instead of Godots appdata. Have a `godots.cfg` in the project folder containing "version=3.5.3-stable" or whatever other config that Godots can use. This file can then be checked into version control so myself and others know the exact version when importing the project into Godots.

**Comment by MakovWait** [comment]
I like the idea. 
Now we infer the editor version from project.godot::config_version property and it is pure guessing, but the approach you offer should make things more precise. 

For now I think it will be:
```gdscript
# res://.godots
version_hint="3.5.3 stable" # just a set of keywords like 0.0.0 (to guess version) etc. 
```

`version_hint` then will be used:

- in guessing the most appropriate editor to bind https://github.com/MakovWait/godots/blob/bcff4ba2b2142dc39b05b209ab52c4728faab0c8/src/services/projects.gd#L315
- as an additional ui field (Projects List, Bind Editor Popup etc.)

**Comment by MakovWait** [comment]
One more approach: use project.godot file and store related settings under [godots] section.
Now I am wondering..

**Comment by denovodavid** [comment]
Actually yeah, for some reason I thought Godot would delete unrecognised options in `project.godot`, but it seems to maintain them, plus you can edit them in the Project Settings window. That could work much more seamlessly :)
