### ISSUE TITLE
The import editor ok button cannot be clicked! why is that?

### ISSUE THREAD

**Issue by ice-ko** [MakovWait/godots#25]
![微信截图_20231006001258](https://github.com/MakovWait/godots/assets/20471045/cdfffc44-2464-416c-ba14-f3c0ef94f337)

**Comment by MakovWait** [comment]
It is a bug :( To avoid it, you can type something to Editor Name LineEdit.

**Comment by ice-ko** [comment]
> It is a bug :( To avoid it, you can type something to Editor Name LineEdit.

That's really it, thank you
