### ISSUE TITLE
[feature request] it should be possible to select installationfolder

### ISSUE THREAD

**Issue by c0d3r9** [MakovWait/godots#33]
Topic says all. (i would put it on a stick too (windows in my case))
And maybe an option to set several links which can scanned for godot files because 
in the news section down-left in the news we can see the new 4.2 beta1 but there is no link because
its a github download location.
Okay manual download works.

Btw. nice piece of software.

**Comment by MakovWait** [comment]
What do you mean by 'installation folder'? If we are talking about the destination, where the downloaded editor is placed - we have this option in settings under 'Advanced/Versions Path'.

TuxFamilty mirror is experiencing bad time right now sadly. 
For now, you are able to use 'Direct Link' or 'Import' (via Drag&Drop even) options.
In the future, the Github mirror will replace the Tuxfamily one when certain conditions are met.

**Comment by c0d3r9** [comment]
I saw the Setting to late. Maybe a red tool icon!?!
