### ISSUE TITLE
Feature request: Defaulting the editor path during installation

### ISSUE THREAD

**Issue by KMouratidis** [MakovWait/godots#4]
When installing an editor, after it's done downloading, you're getting this menu:

![image](https://github.com/MakovWait/godots/assets/26832680/807ffb5e-f587-442a-9d50-d4a943e3eebd)

Then you need to click on the folder icon and pick one of the two files here:

![image](https://github.com/MakovWait/godots/assets/26832680/7f6653ca-c94b-4e89-a7df-6aa79af0ef93)

Can you make it not ask and just pick one by default, and then use the regular or the console version at project launch time, with a checkbox or something?

**Comment by MrEliptik** [comment]
Or make the prompt more explicit. The first time I thought I was able to choose my location so I was confused. I didn't get that I was choosing between two versions

**Comment by Festerdam** [comment]
For remote editors we could probably infer the path and name, so we don't need the import dialogue. If the users desire to run the editor with a shell then we could add a setting for the user to set a preferred terminal emulator and a button/option to run the editor from a shell (on mac we can default to the standard terminal and on windows we can set `open_console` to `true` when running the editor with `OS.create_process`).
