### ISSUE TITLE
Unchecking any platform makes mono builds disappear

### ISSUE THREAD

**Issue by DeeJayLSP** [MakovWait/godots#49]
Any platform checked:
![image](https://github.com/MakovWait/godots/assets/60024671/d035b798-de39-4f6d-9fd3-a6eae6f51b77)

Unchecked:
![image](https://github.com/MakovWait/godots/assets/60024671/0035d4a6-a66f-4185-946c-7065ea304679)

**Comment by MakovWait** [comment]
Thanks!
