### ISSUE TITLE
Add "Open Project Folder" Option to open project directory in the project manager

### ISSUE THREAD

**Issue by AdilDevStuff** [MakovWait/godots#54]
Add an option to open the selected project folder to view its content or for deleting project files in the sidebar.

Example Screenshot (position can be up there with "Edit" & "Run" Button):
![image](https://github.com/MakovWait/godots/assets/94475453/f2f1ed6f-0b43-4e1b-b9d6-05caef695073)

**Comment by MakovWait** [comment]
The feature is already implemented via this button:
![image](https://github.com/MakovWait/godots/assets/39778897/8f4e464f-46a4-4069-ae3e-c09355f21726)

Any reason to add it also to the side bar?

**Comment by AdilDevStuff** [comment]
oh wait.. Damn, i didn't knew about that...its not so much noticeable lol... ig its alright then!
