### ISSUE TITLE
Add the ability to select renderer when creating new project

### ISSUE THREAD

**Issue by AdilDevStuff** [MakovWait/godots#71]
Add the ability to select the renderer when creating a new project.

Like in the project manager of godot.
![image](https://github.com/MakovWait/godots/assets/94475453/517ef84a-f49f-4510-bc6f-8cfa0a86e3a4)

# Why this is needed?
Currently, the project is created with the forward+ renderer by default but someone who wishes to use other renderer method (Mobile or Compatibility) have to first create the project using forward+ and then switch it again which waste sometime. 

This issue proposes the godot project manager's like renderer selection interface to select the desired renderer at project creation phase to save some time.

**Comment by BasilYes** [comment]
It's important because some pc can't even run project on Forward+ (no Vulcan support on device)
