### ISSUE TITLE
Feature Removed (accidentally ?) :  Per project binding extra argument is lost in 1.3 release

### ISSUE THREAD

**Issue by SeremTitus** [MakovWait/godots#81]
<img width="487" alt="asForEditors" src="https://github.com/MakovWait/godots/assets/58259212/d47a48f6-ae35-4c44-9c4b-f8d87e5494b5">

- As it exist for editors. It also exist for individual projects

**Comment by MakovWait** [comment]
We've never had extra args in projects. May be you are talking about 'View Command'? In 1.3 it is called 'Edit Commands' - the last section of RMB popup.

**Comment by SeremTitus** [comment]
<img width="299" alt="Capture" src="https://github.com/MakovWait/godots/assets/58259212/6396bcb8-a123-4e97-9765-dfdf3a1432a6">

- Ohh yeah I was looking for this panel
