### ISSUE TITLE
[Idea] Minimize to Tray/Close

### ISSUE THREAD

**Issue by gro-david** [MakovWait/godots#94]
What about a minimize to tray (or even close feature) when opening a project either to run it or to edit it. Afterwards the Godots window is not really useful since most people will not be opening more than 1 project at any given time. 

For minimizing to tray i found this addon https://github.com/newjoker6/Godot-System-Tray since Godot does not support it natively.

For closing thats really just the matter of adding get_tree().quit() and maybe disowning the Godot processes.

**Comment by MakovWait** [comment]
Auto-closing is configurable via Settings > Application/Config/Auto Close

System tray is interesting, but for implementing this I would like to wait for the native support (I don't like the addon needs some .exe to work)
